backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
 
media_folder: "public/images" # Media files will be stored in the repo under images/uploads
public_folder: "../images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    files:
      - label: "About Info"
        name: "about"
        file: "src/data/about/about.json"
        fields: 
          - {label: Description, name: description, widget: string}
          - {label: Breeder Name, name: name, widget: string}
          - {label: Current Location, name: location, widget: string}
          - {label: Health About, name: health, widget: string}
          - {label: Owner Image, name: ownerImage, widget: "image"}
          - {label: Footer Quick Text, name: footerQuick, widget: "string"}
  - name: "header" # Used in routes, e.g., /admin/collections/blog
    label: "Headline" # Used in the UI
    files:
      - label: "Headline Information"
        name: "header"
        file: "src/data/headlines/mainhead.json"
        fields: 
          - {label: Description, name: description, widget: string}
          - {label: Quote, name: quote, widget: string}
          - {label: Headline Image, name: image, widget: "image"}

  - label: "Your Dogs" # Used in routes, e.g., /admin/collections/blog
    name: "currentDogs" # Used in the UI
    files:
      - name: "Your Dogs Information"
        label: "profiles"
        file: "src/data/dogs/alldogs.json"
        create: true
        fields:
          - label: "Dogs"
            name: allDogs
            widget: list
            fields:
              - { label: Dog Name, name: dogName, widget: string }
              - { label: Dog Title, name: dogTitle, widget: string }
              - { label: Date of Birth, name: dob, widget: date, format: 'L', timeFormat: false  }
              - { label: Profile Image, name: dogProfileImg, widget: image }
              - { label: Banner Image, name: dogBanner, widget: image }
              - { label: Please paste in Vizsla Database link, name: vdLink, widget: string, required: false }
              - { label: Do you have OFA link, name: hasOFA, widget: boolean, required: false }
              - { label: Paste link here, name: ofaLink, widget: string, required: false}
              - { label: Hip Test, name: dogTestHip, widget: string, default: Not Available }
              - { label: Elbow Test, name: dogTestElbows, widget: string, default: Not Available }
              - { label: Eye Test, name: dogTestEye, widget: string, default: Not Available }
              - { label: Thyroid Test, name: dogTestThyroid, widget: string, default: Not Available }
              - { label: Heart Test, name: dogTestHeart, widget: string, default: Not Available }
              - { label: Dam, name: dogDam, widget: string, required: false }
              - { label: Does this Dam have Vizsla Database?, name: hasDamPedigree, widget: boolean, required: false, hint: "This allows a button to appear next to the name of the dog, that leads to vizsla database." }
              - { label: Insert Dam Vizsla Database link, name: damLink, widget: string, required: false  }
              - { label: Sire, name: dogSire, widget: string, required: false }
              - { label: Does this Sire have Vizsla Database?, name: hasSirePedigree, widget: boolean, required: false  }
              - { label: Insert Sire Vizsla Database link, name: sireLink, widget: string, required: false }
              - { label: Does your dog have any Accomplishments, name: hasAccomplished, widget: boolean }
              - { label: Accomplishments, 
                  name: accomplished, 
                  widget: list,
                  field: { label: Accomplishment, name: accomp, widget: string } }
              
              
          
           