backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
 
media_folder: "../images" # Media files will be stored in the repo under images/uploads
public_folder: "../images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    files:
      - label: "About Info"
        name: "about"
        file: "src/data/about/about.json"
        fields: 
          - {label: Description, name: description, widget: string}
          - {label: Breeder Name, name: name, widget: string}
          - {label: Current Location, name: location, widget: string}
          - {label: Health About, name: health, widget: string}
          - {label: Owner Image, name: ownerImage, widget: "image"}

  - name: "header" # Used in routes, e.g., /admin/collections/blog
    label: "Headline" # Used in the UI
    files:
      - label: "Headline Information"
        name: "header"
        file: "src/data/headlines/mainhead.json"
        fields: 
          - {label: Description, name: description, widget: string, default: "Please use a small amount of words..."}
          - {label: Quote, name: quote, widget: string}
           